@startuml

class InventoryTracker {
    start()
    main()
}

class MainWindowController {

    + MainWindowController()

    addNewItemButtonClicked(EventHandler)
    deleteSelectedItemButtonClicked((EventHandler)
    saveAsHtmlButtonClicked(EventHandler)
    saveAsTsvButtonClicked(EventHandler)


    addItem(String, String, BigDecimal)
    editItem()
    saveInventoryAsCSV(filename: String)
    saveInventoryAsHTML(filename: String)
    saveInventoryAsJSON(filename: String)

    - ObservableList<Item>
}

class Item {
    - name: SimpleStringProperty
    - serialNumber: SimpleStringProperty
    - value: SimpleStringProperty

    + getName()
    + setName()
    + nameProperty()
    + getSerialNumber()
    '...
}

class FileManager {
    saveAsCSV(filename: String, data: String)
    saveAsHTML(filename: String, data: String)
    saveAsJSON(filename: String, data: String)
}

openjfx.org.Application <|-- InventoryTracker
InventoryTracker -- MainWindowController
MainWindowController - FileManager
MainWindowController o-- Item
@enduml